// Code generated by protoc-gen-go.
// source: main.proto
// DO NOT EDIT!

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Bar struct {
	One string `protobuf:"bytes,1,opt,name=one" json:"one,omitempty"`
}

func (m *Bar) Reset()                    { *m = Bar{} }
func (m *Bar) String() string            { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()               {}
func (*Bar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Foo struct {
	Bar   *Bar   `protobuf:"bytes,1,opt,name=bar" json:"bar,omitempty"`
	Two   string `protobuf:"bytes,2,opt,name=two" json:"two,omitempty"`
	Three uint64 `protobuf:"varint,3,opt,name=three" json:"three,omitempty"`
}

func (m *Foo) Reset()                    { *m = Foo{} }
func (m *Foo) String() string            { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()               {}
func (*Foo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Foo) GetBar() *Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

func init() {
	proto.RegisterType((*Bar)(nil), "main.Bar")
	proto.RegisterType((*Foo)(nil), "main.Foo")
}

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x84, 0xb8, 0x98, 0x9d, 0x12,
	0x8b, 0x84, 0xb8, 0xb9, 0x98, 0xf3, 0xf3, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x95, 0x2c,
	0xb9, 0x98, 0xdd, 0xf2, 0xf3, 0x85, 0xc4, 0xb8, 0x98, 0x93, 0x12, 0x8b, 0xc0, 0x62, 0xdc, 0x46,
	0x9c, 0x7a, 0x60, 0xad, 0x50, 0xb5, 0x25, 0xe5, 0xf9, 0x12, 0x4c, 0x20, 0xb5, 0x42, 0xbc, 0x5c,
	0xac, 0x25, 0x19, 0x45, 0xa9, 0xa9, 0x12, 0xcc, 0x40, 0x2e, 0x4b, 0x12, 0x1b, 0xd8, 0x6c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0xa9, 0xc5, 0xd2, 0x69, 0x00, 0x00, 0x00,
}
