language: go
sudo: false
go:
  - 1.3
  - 1.4
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
before_script:
  - mkdir -p ${GOPATH}/src/go.pedge.io
  - ln -s ${GOPATH}/src/github.com/peter-edge/go-protolog ${GOPATH}/src/go.pedge.io/protolog
script:
  - go test -test.v ./...
