// Code generated by protoc-gen-go.
// source: proto/testing/testing.proto
// DO NOT EDIT!

package protoliontesting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Foo struct {
	One         string `protobuf:"bytes,1,opt,name=one" json:"one,omitempty"`
	Two         int32  `protobuf:"varint,2,opt,name=two" json:"two,omitempty"`
	StringField string `protobuf:"bytes,3,opt,name=string_field,json=stringField" json:"string_field,omitempty"`
	Int32Field  int32  `protobuf:"varint,4,opt,name=int32_field,json=int32Field" json:"int32_field,omitempty"`
	Bar         *Bar   `protobuf:"bytes,5,opt,name=bar" json:"bar,omitempty"`
}

func (m *Foo) Reset()                    { *m = Foo{} }
func (m *Foo) String() string            { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()               {}
func (*Foo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Foo) GetBar() *Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

type Bar struct {
	One         string `protobuf:"bytes,1,opt,name=one" json:"one,omitempty"`
	Two         string `protobuf:"bytes,2,opt,name=two" json:"two,omitempty"`
	StringField string `protobuf:"bytes,3,opt,name=string_field,json=stringField" json:"string_field,omitempty"`
	Int32Field  int32  `protobuf:"varint,4,opt,name=int32_field,json=int32Field" json:"int32_field,omitempty"`
}

func (m *Bar) Reset()                    { *m = Bar{} }
func (m *Bar) String() string            { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()               {}
func (*Bar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Baz struct {
	Bat *Baz_Bat `protobuf:"bytes,1,opt,name=bat" json:"bat,omitempty"`
}

func (m *Baz) Reset()                    { *m = Baz{} }
func (m *Baz) String() string            { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()               {}
func (*Baz) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Baz) GetBat() *Baz_Bat {
	if m != nil {
		return m.Bat
	}
	return nil
}

type Baz_Bat struct {
	Ban *Baz_Bat_Ban `protobuf:"bytes,1,opt,name=ban" json:"ban,omitempty"`
}

func (m *Baz_Bat) Reset()                    { *m = Baz_Bat{} }
func (m *Baz_Bat) String() string            { return proto.CompactTextString(m) }
func (*Baz_Bat) ProtoMessage()               {}
func (*Baz_Bat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Baz_Bat) GetBan() *Baz_Bat_Ban {
	if m != nil {
		return m.Ban
	}
	return nil
}

type Baz_Bat_Ban struct {
	StringField string `protobuf:"bytes,1,opt,name=string_field,json=stringField" json:"string_field,omitempty"`
	Int32Field  int32  `protobuf:"varint,2,opt,name=int32_field,json=int32Field" json:"int32_field,omitempty"`
}

func (m *Baz_Bat_Ban) Reset()                    { *m = Baz_Bat_Ban{} }
func (m *Baz_Bat_Ban) String() string            { return proto.CompactTextString(m) }
func (*Baz_Bat_Ban) ProtoMessage()               {}
func (*Baz_Bat_Ban) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type NoStdJson struct {
	One map[uint64]string `protobuf:"bytes,1,rep,name=one" json:"one,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *NoStdJson) Reset()                    { *m = NoStdJson{} }
func (m *NoStdJson) String() string            { return proto.CompactTextString(m) }
func (*NoStdJson) ProtoMessage()               {}
func (*NoStdJson) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NoStdJson) GetOne() map[uint64]string {
	if m != nil {
		return m.One
	}
	return nil
}

func init() {
	proto.RegisterType((*Foo)(nil), "lion.proto.testing.Foo")
	proto.RegisterType((*Bar)(nil), "lion.proto.testing.Bar")
	proto.RegisterType((*Baz)(nil), "lion.proto.testing.Baz")
	proto.RegisterType((*Baz_Bat)(nil), "lion.proto.testing.Baz.Bat")
	proto.RegisterType((*Baz_Bat_Ban)(nil), "lion.proto.testing.Baz.Bat.Ban")
	proto.RegisterType((*Empty)(nil), "lion.proto.testing.Empty")
	proto.RegisterType((*NoStdJson)(nil), "lion.proto.testing.NoStdJson")
}

func init() { proto.RegisterFile("proto/testing/testing.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x99, 0x4e, 0xf3, 0xff, 0xf6, 0xc6, 0x45, 0x19, 0x04, 0x43, 0xba, 0xa8, 0x66, 0x21,
	0xba, 0x30, 0x62, 0x0a, 0x52, 0x5c, 0x16, 0x5a, 0xd0, 0x85, 0x42, 0xdc, 0xb9, 0x91, 0x94, 0x8e,
	0x12, 0x4c, 0x67, 0x4a, 0x72, 0x55, 0x52, 0x70, 0xe5, 0x4b, 0xf8, 0x2c, 0x3e, 0x9d, 0x73, 0x27,
	0x89, 0x9b, 0x94, 0xba, 0x71, 0x31, 0xe4, 0xe6, 0xcc, 0x39, 0x9c, 0x8f, 0x3b, 0x30, 0x58, 0xe5,
	0x1a, 0xf5, 0x19, 0xca, 0x02, 0x53, 0xf5, 0xd4, 0x7c, 0x43, 0xab, 0x0a, 0x91, 0xa5, 0x5a, 0x55,
	0x73, 0x58, 0xdf, 0x04, 0x9f, 0x0c, 0xf8, 0x4c, 0x6b, 0xd1, 0x07, 0xae, 0x95, 0xf4, 0xd8, 0x01,
	0x3b, 0xee, 0xc5, 0x34, 0x92, 0x82, 0x6f, 0xda, 0xeb, 0x18, 0xc5, 0x89, 0x69, 0x14, 0x87, 0xb0,
	0x5b, 0x60, 0x6e, 0x52, 0x0f, 0x8f, 0xa9, 0xcc, 0x16, 0x1e, 0xb7, 0x66, 0xb7, 0xd2, 0x66, 0x24,
	0x89, 0x21, 0xb8, 0xa9, 0xc2, 0x51, 0x54, 0x3b, 0xba, 0x36, 0x0c, 0x56, 0xaa, 0x0c, 0x27, 0xc0,
	0xe7, 0x49, 0xee, 0x39, 0xe6, 0xc2, 0x8d, 0xf6, 0xc3, 0x36, 0x51, 0x38, 0x49, 0xf2, 0x98, 0x3c,
	0xc1, 0x12, 0xb8, 0x99, 0xb7, 0x93, 0xf5, 0xfe, 0x8c, 0x2c, 0xf8, 0x62, 0xd4, 0xb7, 0x16, 0xa7,
	0x44, 0x88, 0xb6, 0xcf, 0x8d, 0x06, 0x9b, 0x09, 0xd7, 0xe6, 0x20, 0x51, 0xa2, 0xff, 0x61, 0x63,
	0x28, 0xce, 0x29, 0xa6, 0xea, 0xd8, 0x70, 0x4b, 0xcc, 0x1c, 0x45, 0x51, 0xe5, 0x5f, 0x51, 0x52,
	0xb5, 0xe0, 0xd9, 0xaf, 0xf0, 0x9d, 0x16, 0xfc, 0x7f, 0x70, 0xa6, 0xcb, 0x15, 0x96, 0xc1, 0x3b,
	0xf4, 0x6e, 0xf4, 0x1d, 0x2e, 0xae, 0x0b, 0xad, 0xc4, 0xb8, 0x59, 0x1d, 0x37, 0x4c, 0x47, 0x9b,
	0x98, 0x7e, 0xbc, 0xe1, 0xad, 0x92, 0x53, 0x85, 0x79, 0x69, 0x57, 0xec, 0x5f, 0xc0, 0x4e, 0x23,
	0xd0, 0xba, 0x9f, 0x65, 0x69, 0xb1, 0xba, 0x31, 0x8d, 0x62, 0x0f, 0x9c, 0xd7, 0x24, 0x7b, 0x91,
	0xf5, 0x13, 0x54, 0x3f, 0x97, 0x9d, 0x31, 0x9b, 0x88, 0xfb, 0xbe, 0x2d, 0xa0, 0xaa, 0xba, 0x63,
	0xfe, 0xcf, 0x2a, 0xa3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x9f, 0x6b, 0xa1, 0x9c, 0x02,
	0x00, 0x00,
}
